### ISSUE TITLE
Surpass faction system

### ISSUE THREAD

**Issue by tdelc** [elptito/EmptyEpsilon#124]
From now, faction are fixed and their opinion between each other too. In a LARP perspective, faction can change their opinions, and some ship from a faction can betrayed it.
So, faction has to be modify by GM or scripts (amir arad did this) and ship must have a personality (pacifist : don't attack anything, normal : attack based on faction , aggressif : attack everything except its faction , solo : attack anything).

Risk :  Solo ships can attack each other. Possible solution : Solo ships attack anyone except solo ships.

**Comment by tdelc** [comment]
Remark from point zero : need to add 
'if (P<Asteroid>(space_object))
            continue;'
in findbestTarget function of IA. Because IA ship will attack every Asteroid they will see...

Same function, add : 
'if (P<MissileWeapon>(target))
        score -= 15000;'
to avoid missile distraction if missile can be targetable (another issue)

**Comment by amir-arad** [comment]
this is the PR for the factions tweak: daid/EmptyEpsilon#653
Warning: adding too many factions results in unstable server.

**Comment by tdelc** [comment]
Thanks a lot, I think I will directly copy-paste your code. It is a very nice way to control faction interaction !

**Comment by tdelc** [comment]
Closed with https://github.com/tdelc/EmptyEpsilon/commit/6ac0b9f8d99e75ad319884701c6d6a061365b0ae
Thanks a lot @amir-arad , your system work perfectly :+1:
