### ISSUE TITLE
Enable joystick button from EE

### ISSUE THREAD

**Issue by tdelc** [elptito/EmptyEpsilon#176]
Test if it is possible to automatic button from joystick to shorcuts for EE

**Comment by amir-arad** [comment]
it's possible, I've added it in daid/EmptyEpsilon#656 and use it extensively. It's in your code too.
see example config in [my repo](https://github.com/amir-arad/EmptyEpsilon/blob/master/options.ini). `[B0]` means button 0 on any joystick. `[J1];[B3]` mean button 3 on joystick 1.

**Comment by tdelc** [comment]
Perfect, thanks a lot, it is exactly what i need.
I will implement this during this month with all the shorcuts #174

**Comment by tdelc** [comment]
Ok, after some tests, all is alright !! Thanks a lot @amir-arad
