### ISSUE TITLE
WARP shut down the main screen

### ISSUE THREAD

**Issue by tdelc** [elptito/EmptyEpsilon#191]
The side main screen still work.

**Comment by amir-arad** [comment]
should pay attention to the graphic card - does it fail only on computers with nvidia GPU?

**Comment by tdelc** [comment]
I don t think so, because all worked fine before my last release...

**Comment by tdelc** [comment]
I cannot understand because it worked before, but now, with warp_post_processor_enabled=1, it is ok. So it is fine ^^
